project_id = "blimqfbmrbqvmbqrzpem"

[functions.weather]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.market-prices]
verify_jwt = false

[functions.analyze-plant]
verify_jwt = false
